#' Example Protein Groups MaxQuant output table that can be processed using this package.
#'
#' @format Data frames, as generated by MaxQuant. Details of output tables can
#' be found at:
#' \url{http://www.coxdocs.org/doku.php?id=maxquant:table:proteingrouptable}
#' @source Internal (CFR lab) mass spec experiment, processed by MaxQuant

"proteinGroups"

#' Example STY MaxQuant output table that can be processed using this package.
#'
#' @format Data frames, as generated by MaxQuant. Details of output tables can
#' be found at:
#' \url{http://www.coxdocs.org/doku.php?id=maxquant:table:sitetable}
#' @source Internal (CFR lab) mass spec experiment, processed by MaxQuant
"phosphoSTYSites"

#' Example Modification Specific Peptides MaxQuant output table
#'  that can be processed using this package.
#'
#' @format Data frames, as generated by MaxQuant. Details of output tables can
#' be found at:
#' \url{http://www.coxdocs.org/doku.php?id=maxquant:table:modificationspecificpeptidetable}
#' @source Internal (CFR lab) mass spec experiment, processed by MaxQuant
"modificationSpecificPeptides"

#' Example Evidence MaxQuant output table that can be processed using this package.
#'
#' @format Data frames, as generated by MaxQuant. Details of output tables can
#' be found at:
#' \url{http://www.coxdocs.org/doku.php?id=maxquant:table:evidencetable}
#' @source Internal (CFR lab) mass spec experiment, processed by MaxQuant
"evidence"

#' Example Peptide MaxQuant output table that can be processed using this package.
#'
#' @format Data frames, as generated by MaxQuant. Details of output tables can
#' be found at:
#' \url{http://www.coxdocs.org/doku.php?id=maxquant:table:peptidetable}
#' @source Internal (CFR lab) mass spec experiment, processed by MaxQuant
"peptides"
